# ref callback 사용법 고려
HelloMandu/javascript-deep-dive pull request #18
Opened 2021-11-01 10:34 UTC by ghooz1204

2021-11-01 10:36 UTC, HelloMandu requested changes

2021-11-01 10:36 UTC, HelloMandu commented on README.md
> +- 자유롭게 개발하면서 새롭게 알게된 부분이나 몰랐던 지식을 공유하기
rebase를 안햇구먼

2021-11-01 11:59 UTC, ghooz1204 commented on README.md
> +- 자유롭게 개발하면서 새롭게 알게된 부분이나 몰랐던 지식을 공유하기
??

2021-11-01 12:02 UTC, HelloMandu approved these changes
LGTM

2021-11-02 04:10 UTC, SewookHan approved these changes

2021-11-14 00:06 UTC, merged